version: '3.6'

services:
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    user: postgres
    image: postgres:latest
    networks:
      - default
    ports:
      - 5600:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always


  basehabilis:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db:5432/test
    networks:
      - default
    dns:
      - 8.8.8.8
    ports:
      - 5100:5100
    restart: always