version: '3.8'

services:

  db:
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    image: postgres:latest
    env_file: .env.dev
    networks:
      - default
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "basehabilis" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  basehabilis:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/$POSTGRES_DB
    env_file: .env.dev
    networks:
      - default
    expose:
      - 5000
    restart: always