version: '3.6'

services:
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5600:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  basehabilis:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db:5432/test
    env_file: .env
    networks:
      - default
    ports:
      - 5100:5100
    restart: always
    volumes:
    - ./anhtropos-files:/home/anthropos/anthropos/static/files