services:

  db:
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    image: postgres:16
    networks:
      - default
    ports:
      - 51432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "basehabilis" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  basehabilis:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "flask db upgrade | gunicorn -w 2 -b :5000 --access-logfile - --error-logfile - base_habilis:app"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/$POSTGRES_DB
    env_file: .env
    networks:
      - default
    expose:
      - 5000
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw